package com.thepacific.mvp;

public enum DisposeEvent {
    ACTIVITY_PAUSE,
    ACTIVITY_STOP,
    ACTIVITY_DESTROY,
    FRAGMENT_PAUSE,
    FRAGMENT_STOP,
    FRAGMENT_DESTROY_VIEW,
    FRAGMENT_DESTROY,
    FRAGMENT_DETACH,
}
