package com.thepacific.presentation.core;

public enum Event {
  ACTIVITY_CREATE,
  ACTIVITY_START,
  ACTIVITY_RESUME,
  ACTIVITY_PAUSE,
  ACTIVITY_STOP,
  ACTIVITY_DESTROY,

  FRAGMENT_CREATE,
  FRAGMENT_START,
  FRAGMENT_RESUME,
  FRAGMENT_PAUSE,
  FRAGMENT_STOP,
  FRAGMENT_DESTROY,

  DIALOG_CREATE,
  DIALOG_START,
  DIALOG_RESUME,
  DIALOG_PAUSE,
  DIALOG_STOP,
  DIALOG_DESTROY,

  ANY
}
